### ISSUE TITLE
Quesion: Is it possible to implement variables into the command the rcon sends (such as the commit ID/commit author)?

### ISSUE THREAD

**Issue by ApplecakeYT** [Plagiatus/RCON-Action#1]

**Comment by Plagiatus** [comment]
what kind of variables would you like to have access to? Or what would you think would be helpful?

I think this is a good idea, but I'm kind of torn between various options:

1. giving access to all contexts, including both [webhook](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads) and [general options](https://docs.github.com/en/actions/learn-github-actions/contexts), putting the risk fully into the gits hands. However, since actions are generally set-able by all contributors, this would pose a security risk as attackers could get secrets put into the server output that way.  
2. Thus, the next option would be to allow all contexts, but sanitize them to avoid potentially secret information from being used. However, I don't trust myself to find and properly remove all possible harmful information. It also would potentially leave the door open to [script injection](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections), both in the action and on the server itself.  
3. Which leaves me with only the last option: allow for some specifically preconfigured values. But then which ones are the most likely to be needed?

So yeah, I'm leaning heavily towards #3, do you have any inputs as to which values you'd like to have access to?

**Comment by ApplecakeYT** [comment]
I would preferably like access to GitHub's Environment Variables. https://docs.github.com/en/actions/learn-github-actions/environment-variables.

**Comment by ApplecakeYT** [comment]
Are you gonna apply all of them or just a few?

**Comment by Plagiatus** [comment]
I think I will try to apply all of the general env variables for now, see how it works out. I'll be running some tests on the `env-variables` branch in the coming days hopefully - feel free to remind me again if I forget about it (again). 😅

**Comment by Plagiatus** [comment]
Okay, turns out you can already use env variables to your hearts content, you just need to use [context properties](https://docs.github.com/en/actions/learn-github-actions/contexts) notation instead.

### Examples:

Runtime variables:

```yml
commands: '["say actor ${{ github.actor }}"]'
```
![image](https://user-images.githubusercontent.com/7681159/203531828-37b3b87c-d009-4266-b987-f2d45eda09e3.png)


Custom Variables:
```yml
env:
  DAY_OF_WEEK: Monday

...
commands: '["say day ${{env.DAY_OF_WEEK}}"]'
```
![image](https://user-images.githubusercontent.com/7681159/203531474-e763c776-a635-4394-8a21-c370e5047333.png)

So yeah, no change necessary, works out of the box (also with secrets, and they are not censored, so be careful!).

**Comment by ApplecakeYT** [comment]
How would I implement this into commands that contain Json elements?

For Example,
`
env:
  DAY_OF_WEEK: Monday

...
commands: '["tellraw @a ["The day is ${{env.DAY_OF_WEEK}}"]"]'
`
